### ISSUE TITLE
Only front camera.

### ISSUE THREAD

**Issue by weetameal** [aigenseer/input-scanner#1]
Hye, thank you for the plugin. I have tried in for my website. However, it only allow for front camera. Do you have any idea how I can change it to only use rear camera?

**Comment by aigenseer** [comment]
hello @weetameal, 
I found the error and fixed it. Please test it again. Make sure to clear your browser cache beforehand in order to receive the new version.

**Comment by weetameal** [comment]
It now working wonderful. Thank you so much & sorry for late response.
